/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;
/**
 *
 * @author Cecilia
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButtonTurista = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonAgencia = new javax.swing.JToggleButton();
        jButtonTransporte = new javax.swing.JToggleButton();
        jButtonAlojamiento = new javax.swing.JToggleButton();
        jPanelTurista = new javax.swing.JPanel();
        jTextDestino = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboTipoAlojamiento = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonAEstrella1 = new javax.swing.JRadioButton();
        jButtonAEstrella2 = new javax.swing.JRadioButton();
        jButtonAEstrella3 = new javax.swing.JRadioButton();
        jButtonAEstrella4 = new javax.swing.JRadioButton();
        jButtonAEstrella5 = new javax.swing.JRadioButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonTEstrella1 = new javax.swing.JRadioButton();
        jButtonTEstrella2 = new javax.swing.JRadioButton();
        jButtonTEstrella3 = new javax.swing.JRadioButton();
        jButtonTEstrella4 = new javax.swing.JRadioButton();
        jButtonTEstrella5 = new javax.swing.JRadioButton();
        jComboTipoTransporte = new javax.swing.JComboBox();
        jButtonCrearAgente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jButtonInfoAlojamiento = new javax.swing.JButton();
        jButtonInfoTranporte = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerCantPersonas = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jSpinnerCantDias = new javax.swing.JSpinner();
        jButtonCrearAgente1 = new javax.swing.JButton();
        jTextPrecioAlojamiento = new javax.swing.JFormattedTextField();
        jTextPrecioTransporte = new javax.swing.JFormattedTextField();
        jLabelAdvertenciaDestino = new javax.swing.JLabel();
        jLabelAdvertenciaPrecioA = new javax.swing.JLabel();
        jLabelAdvertenciaPrecioT = new javax.swing.JLabel();
        jPanelAgencia = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSliderPonderacion = new javax.swing.JSlider();
        jButtonCrearAgencia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanelTransporte = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanelAlojamiento = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuItemAdmin = new javax.swing.JCheckBoxMenuItem();
        jMenuItemJADE = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMA Agentes de Turismo");
        setResizable(false);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(250, 32769));
        jToolBar1.add(jSeparator3);

        jButtonTurista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/User24.png"))); // NOI18N
        jButtonTurista.setSelected(true);
        jButtonTurista.setText("Turista");
        jButtonTurista.setFocusable(false);
        jButtonTurista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTurista.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonTurista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTuristaActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonTurista);
        jToolBar1.add(jSeparator1);

        jButtonAgencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/User24.png"))); // NOI18N
        jButtonAgencia.setText("Agencia");
        jButtonAgencia.setEnabled(false);
        jButtonAgencia.setFocusable(false);
        jButtonAgencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAgencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgenciaActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAgencia);

        jButtonTransporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/User24.png"))); // NOI18N
        jButtonTransporte.setText("Transporte");
        jButtonTransporte.setEnabled(false);
        jButtonTransporte.setFocusable(false);
        jButtonTransporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTransporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransporteActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonTransporte);

        jButtonAlojamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Home24.png"))); // NOI18N
        jButtonAlojamiento.setText("Alojamiento");
        jButtonAlojamiento.setEnabled(false);
        jButtonAlojamiento.setFocusable(false);
        jButtonAlojamiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAlojamiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlojamientoActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAlojamiento);

        jPanelTurista.setPreferredSize(new java.awt.Dimension(264, 472));

        jTextDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDestinoActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo");
        jLabel2.setFocusable(false);

        jComboTipoAlojamiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hotel", "Hostel", "Departamento", "Cabaña" }));
        jComboTipoAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoAlojamientoActionPerformed(evt);
            }
        });

        jLabel3.setText("Categoría");
        jLabel3.setFocusable(false);

        jLabel5.setText("Precio a pagar");
        jLabel5.setFocusable(false);
        jLabel5.setMaximumSize(new java.awt.Dimension(70, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(70, 14));
        jLabel5.setName(""); // NOI18N

        jButtonAEstrella1.setSelected(true);
        jButtonAEstrella1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_empty16.png"))); // NOI18N
        jButtonAEstrella1.setName(""); // NOI18N
        jButtonAEstrella1.setRolloverEnabled(false);
        jButtonAEstrella1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_full16.png"))); // NOI18N
        jButtonAEstrella1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAEstrella1ActionPerformed(evt);
            }
        });

        jButtonAEstrella2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_empty16.png"))); // NOI18N
        jButtonAEstrella2.setRolloverEnabled(false);
        jButtonAEstrella2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_full16.png"))); // NOI18N
        jButtonAEstrella2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAEstrella2ActionPerformed(evt);
            }
        });

        jButtonAEstrella3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_empty16.png"))); // NOI18N
        jButtonAEstrella3.setRolloverEnabled(false);
        jButtonAEstrella3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_full16.png"))); // NOI18N
        jButtonAEstrella3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAEstrella3ActionPerformed(evt);
            }
        });

        jButtonAEstrella4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_empty16.png"))); // NOI18N
        jButtonAEstrella4.setRolloverEnabled(false);
        jButtonAEstrella4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_full16.png"))); // NOI18N
        jButtonAEstrella4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAEstrella4ActionPerformed(evt);
            }
        });

        jButtonAEstrella5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_empty16.png"))); // NOI18N
        jButtonAEstrella5.setRolloverEnabled(false);
        jButtonAEstrella5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_full16.png"))); // NOI18N
        jButtonAEstrella5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAEstrella5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo");
        jLabel7.setFocusable(false);

        jLabel8.setText("Categoría");
        jLabel8.setFocusable(false);
        jLabel8.setMaximumSize(new java.awt.Dimension(70, 14));
        jLabel8.setMinimumSize(new java.awt.Dimension(70, 14));

        jLabel9.setText("Precio a pagar");
        jLabel9.setFocusable(false);
        jLabel9.setMaximumSize(new java.awt.Dimension(70, 14));
        jLabel9.setMinimumSize(new java.awt.Dimension(70, 14));

        jButtonTEstrella1.setSelected(true);
        jButtonTEstrella1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_empty16.png"))); // NOI18N
        jButtonTEstrella1.setRolloverEnabled(false);
        jButtonTEstrella1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_full16.png"))); // NOI18N
        jButtonTEstrella1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTEstrella1ActionPerformed(evt);
            }
        });

        jButtonTEstrella2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_empty16.png"))); // NOI18N
        jButtonTEstrella2.setRolloverEnabled(false);
        jButtonTEstrella2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_full16.png"))); // NOI18N
        jButtonTEstrella2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTEstrella2ActionPerformed(evt);
            }
        });

        jButtonTEstrella3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_empty16.png"))); // NOI18N
        jButtonTEstrella3.setRolloverEnabled(false);
        jButtonTEstrella3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_full16.png"))); // NOI18N
        jButtonTEstrella3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTEstrella3ActionPerformed(evt);
            }
        });

        jButtonTEstrella4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_empty16.png"))); // NOI18N
        jButtonTEstrella4.setRolloverEnabled(false);
        jButtonTEstrella4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_full16.png"))); // NOI18N
        jButtonTEstrella4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTEstrella4ActionPerformed(evt);
            }
        });

        jButtonTEstrella5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_empty16.png"))); // NOI18N
        jButtonTEstrella5.setRolloverEnabled(false);
        jButtonTEstrella5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Star_full16.png"))); // NOI18N
        jButtonTEstrella5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTEstrella5ActionPerformed(evt);
            }
        });

        jComboTipoTransporte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Colectivo", "Avión" }));
        jComboTipoTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoTransporteActionPerformed(evt);
            }
        });

        jButtonCrearAgente.setText("Consultar agencias");
        jButtonCrearAgente.setPreferredSize(new java.awt.Dimension(155, 25));
        jButtonCrearAgente.setRequestFocusEnabled(false);
        jButtonCrearAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearAgenteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Transporte");
        jLabel6.setFocusable(false);
        jLabel6.setOpaque(true);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Alojamiento");
        jLabel13.setFocusable(false);
        jLabel13.setOpaque(true);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Destino");
        jLabel14.setFocusable(false);
        jLabel14.setOpaque(true);

        jButtonInfoAlojamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Info16.png"))); // NOI18N
        jButtonInfoAlojamiento.setMaximumSize(new java.awt.Dimension(40, 25));
        jButtonInfoAlojamiento.setMinimumSize(new java.awt.Dimension(40, 25));
        jButtonInfoAlojamiento.setPreferredSize(new java.awt.Dimension(40, 25));
        jButtonInfoAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoAlojamientoActionPerformed(evt);
            }
        });

        jButtonInfoTranporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Info16.png"))); // NOI18N
        jButtonInfoTranporte.setMaximumSize(new java.awt.Dimension(40, 25));
        jButtonInfoTranporte.setMinimumSize(new java.awt.Dimension(40, 25));
        jButtonInfoTranporte.setPreferredSize(new java.awt.Dimension(40, 25));
        jButtonInfoTranporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoTranporteActionPerformed(evt);
            }
        });

        jLabel4.setText("Cantidad de personas");
        jLabel4.setFocusable(false);

        jSpinnerCantPersonas.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jSpinnerCantPersonas.setName(""); // NOI18N

        jLabel15.setText("Cantidad de días");
        jLabel15.setFocusable(false);

        jSpinnerCantDias.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jSpinnerCantDias.setName(""); // NOI18N

        jButtonCrearAgente1.setText("Respuesta");
        jButtonCrearAgente1.setToolTipText("");
        jButtonCrearAgente1.setActionCommand("Respuesta");
        jButtonCrearAgente1.setEnabled(false);
        jButtonCrearAgente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearAgente1ActionPerformed(evt);
            }
        });

        jTextPrecioAlojamiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jTextPrecioAlojamiento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextPrecioAlojamiento.setToolTipText("");
        jTextPrecioAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPrecioAlojamientoActionPerformed(evt);
            }
        });

        jTextPrecioTransporte.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jTextPrecioTransporte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextPrecioTransporte.setToolTipText("");

        jLabelAdvertenciaDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Alert16.png"))); // NOI18N
        jLabelAdvertenciaDestino.setToolTipText("");
        jLabelAdvertenciaDestino.setPreferredSize(new java.awt.Dimension(16, 16));
        jLabelAdvertenciaDestino.setVisible(false);

        jLabelAdvertenciaPrecioA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Alert16.png"))); // NOI18N
        jLabelAdvertenciaPrecioA.setPreferredSize(new java.awt.Dimension(16, 16));
        jLabelAdvertenciaPrecioA.setVisible(false);

        jLabelAdvertenciaPrecioT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Alert16.png"))); // NOI18N
        jLabelAdvertenciaPrecioT.setPreferredSize(new java.awt.Dimension(16, 16));
        jLabelAdvertenciaPrecioT.setVisible(false);

        javax.swing.GroupLayout jPanelTuristaLayout = new javax.swing.GroupLayout(jPanelTurista);
        jPanelTurista.setLayout(jPanelTuristaLayout);
        jPanelTuristaLayout.setHorizontalGroup(
            jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTuristaLayout.createSequentialGroup()
                .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboTipoTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTuristaLayout.createSequentialGroup()
                        .addComponent(jButtonTEstrella1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTEstrella2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTEstrella3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTEstrella4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTEstrella5))
                    .addComponent(jTextPrecioTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAdvertenciaPrecioT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInfoTranporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(jPanelTuristaLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7))
            .addGroup(jPanelTuristaLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6))
            .addGroup(jPanelTuristaLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jButtonCrearAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCrearAgente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelTuristaLayout.createSequentialGroup()
                .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTuristaLayout.createSequentialGroup()
                        .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelTuristaLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(jTextDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTuristaLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinnerCantDias, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelTuristaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinnerCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelAdvertenciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTuristaLayout.createSequentialGroup()
                        .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboTipoAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelTuristaLayout.createSequentialGroup()
                                .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelTuristaLayout.createSequentialGroup()
                                        .addComponent(jButtonAEstrella1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonAEstrella2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonAEstrella3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonAEstrella4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonAEstrella5))
                                    .addComponent(jTextPrecioAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonInfoAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelAdvertenciaPrecioA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTuristaLayout.setVerticalGroup(
            jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTuristaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel14)
                    .addComponent(jTextDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAdvertenciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jSpinnerCantDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboTipoAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jButtonAEstrella1)
                    .addComponent(jButtonAEstrella2)
                    .addComponent(jButtonAEstrella3)
                    .addComponent(jButtonAEstrella4)
                    .addComponent(jButtonAEstrella5)
                    .addComponent(jButtonInfoAlojamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPrecioAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAdvertenciaPrecioA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboTipoTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTEstrella1)
                    .addComponent(jButtonTEstrella2)
                    .addComponent(jButtonTEstrella3)
                    .addComponent(jButtonTEstrella4)
                    .addComponent(jButtonTEstrella5)
                    .addComponent(jButtonInfoTranporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelAdvertenciaPrecioT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPrecioTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelTuristaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrearAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCrearAgente1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelAgencia.setVisible(false);
        jPanelAgencia.setName(""); // NOI18N
        jPanelAgencia.setPreferredSize(new java.awt.Dimension(264, 472));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Ponderación");

        jSliderPonderacion.setMajorTickSpacing(1);
        jSliderPonderacion.setMaximum(10);
        jSliderPonderacion.setMinorTickSpacing(1);
        jSliderPonderacion.setPaintTicks(true);
        jSliderPonderacion.setValue(5);
        jSliderPonderacion.setName(""); // NOI18N

        jButtonCrearAgencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Wheel16.png"))); // NOI18N
        jButtonCrearAgencia.setText("Crear Agencia");
        jButtonCrearAgencia.setToolTipText("");
        jButtonCrearAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearAgenciaActionPerformed(evt);
            }
        });

        jLabel1.setText("Precio");

        jLabel16.setText("Categoría");

        javax.swing.GroupLayout jPanelAgenciaLayout = new javax.swing.GroupLayout(jPanelAgencia);
        jPanelAgencia.setLayout(jPanelAgenciaLayout);
        jPanelAgenciaLayout.setHorizontalGroup(
            jPanelAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderPonderacion, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(jButtonCrearAgencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelAgenciaLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelAgenciaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)))
                .addContainerGap())
        );
        jPanelAgenciaLayout.setVerticalGroup(
            jPanelAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAgenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderPonderacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
                .addComponent(jButtonCrearAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelTransporte.setVisible(false);
        jPanelTransporte.setPreferredSize(new java.awt.Dimension(264, 472));

        jLabel17.setText("Panel  Transporte, en principio no visible");
        jLabel17.setPreferredSize(new java.awt.Dimension(280, 430));

        javax.swing.GroupLayout jPanelTransporteLayout = new javax.swing.GroupLayout(jPanelTransporte);
        jPanelTransporte.setLayout(jPanelTransporteLayout);
        jPanelTransporteLayout.setHorizontalGroup(
            jPanelTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanelTransporteLayout.setVerticalGroup(
            jPanelTransporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransporteLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelAlojamiento.setVisible(false);
        jPanelAlojamiento.setPreferredSize(new java.awt.Dimension(264, 472));
        jPanelAlojamiento.setRequestFocusEnabled(false);

        jLabel12.setText("Panel  Alojamiento, en principio no visible");
        jLabel12.setPreferredSize(new java.awt.Dimension(280, 430));

        javax.swing.GroupLayout jPanelAlojamientoLayout = new javax.swing.GroupLayout(jPanelAlojamiento);
        jPanelAlojamiento.setLayout(jPanelAlojamientoLayout);
        jPanelAlojamientoLayout.setHorizontalGroup(
            jPanelAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlojamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanelAlojamientoLayout.setVerticalGroup(
            jPanelAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlojamientoLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu.setText("Opciones");

        jMenuItemAdmin.setText("Modo Administrador");
        jMenuItemAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdminActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemAdmin);

        jMenuItemJADE.setText("Iniciar Jade GUI");
        jMenuItemJADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemJADEActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemJADE);
        jMenu.add(jSeparator2);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemSalir);

        jMenuBar.add(jMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanelTurista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelTransporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAlojamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTurista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int categoriaAlojamiento(){
        if (jButtonAEstrella5.isSelected()){
            return 5;
        }
        if (jButtonAEstrella4.isSelected()){
            return 4;
        }
        if (jButtonAEstrella3.isSelected()){
            return 3;
        }
        if (jButtonAEstrella2.isSelected()){
            return 2;
        }
        return 1;
    }     
    
    private int categoriaTransporte(){
        if (jButtonTEstrella5.isSelected()){
            return 5;
        }
        if (jButtonTEstrella4.isSelected()){
            return 4;
        }
        if (jButtonTEstrella3.isSelected()){
            return 3;
        }
        if (jButtonTEstrella2.isSelected()){
            return 2;
        }
        return 1;
    } 
    
    
    private void jMenuItemAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdminActionPerformed
    if (jMenuItemAdmin.getState()){
        jButtonAgencia.setEnabled(true);
        jButtonAlojamiento.setEnabled(true);
        jButtonTransporte.setEnabled(true);
    } else {
        jButtonAgencia.setEnabled(false);
        jButtonAlojamiento.setEnabled(false);
        jButtonTransporte.setEnabled(false);
        if (!jPanelTurista.isVisible()){
            jPanelTurista.setVisible(true);
            jPanelAgencia.setVisible(false);
            jPanelTransporte.setVisible(false);
            jPanelAlojamiento.setVisible(false);
            jButtonAgencia.setSelected(false);
            jButtonTransporte.setSelected(false);
            jButtonAlojamiento.setSelected(false);

        }
         
    }
    
    }//GEN-LAST:event_jMenuItemAdminActionPerformed
    
    private void jButtonTuristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTuristaActionPerformed
        if (jButtonTurista.isSelected()&& (!jPanelTurista.isVisible())){
            jPanelTurista.setVisible(true);
            jPanelAgencia.setVisible(false);
            jPanelTransporte.setVisible(false);
            jPanelAlojamiento.setVisible(false);
            jButtonAgencia.setSelected(false);
            jButtonTransporte.setSelected(false);
            jButtonAlojamiento.setSelected(false);
        } else {
        jButtonTurista.setSelected(true);
        }
    }//GEN-LAST:event_jButtonTuristaActionPerformed
    
    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
    System.exit(0);      
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jButtonAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgenciaActionPerformed
        if (jButtonAgencia.isSelected()&& (!jPanelAgencia.isVisible())){
            jPanelAgencia.setVisible(true);
            jPanelTurista.setVisible(false);
            jPanelTransporte.setVisible(false);
            jPanelAlojamiento.setVisible(false);
            jButtonTurista.setSelected(false);
            jButtonTransporte.setSelected(false);
            jButtonAlojamiento.setSelected(false);
        } else {
        jButtonAgencia.setSelected(true);    
        }
    }//GEN-LAST:event_jButtonAgenciaActionPerformed

    private void jButtonTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransporteActionPerformed
        if (jButtonTransporte.isSelected()&& (!jPanelTransporte.isVisible())){
            jPanelTransporte.setVisible(true);
            jPanelTurista.setVisible(false);
            jPanelAgencia.setVisible(false);
            jPanelAlojamiento.setVisible(false);
            jButtonTurista.setSelected(false);
            jButtonAgencia.setSelected(false);
            jButtonAlojamiento.setSelected(false);
        } else {
        jButtonTransporte.setSelected(true);
        }
    }//GEN-LAST:event_jButtonTransporteActionPerformed

    private void jButtonAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlojamientoActionPerformed
        if (jButtonAlojamiento.isSelected()&& (!jPanelAlojamiento.isVisible())){
            jPanelAlojamiento.setVisible(true);
            jPanelTurista.setVisible(false);
            jPanelTransporte.setVisible(false);
            jPanelAgencia.setVisible(false);
            jButtonTurista.setSelected(false);
            jButtonTransporte.setSelected(false);
            jButtonAgencia.setSelected(false);
        } else {
        jButtonAlojamiento.setSelected(true);    
        }
    }//GEN-LAST:event_jButtonAlojamientoActionPerformed

    private void jButtonInfoAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoAlojamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInfoAlojamientoActionPerformed

    private void jButtonCrearAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearAgenteActionPerformed
// Imprime por consola destino-cantPersonas-cantDias-
//                     tipoAlojamiento-categoriaAlojamiento-precioAlojamiento
//                     tipoTransporte-categoriaTransporte-precioTransporte
        
        if ((!"".equals(jTextDestino.getText()))&&(jTextPrecioAlojamiento.getValue()!=null)&&(jTextPrecioTransporte.getValue()!=null)) {
            System.out.println(
                jTextDestino.getText()+"-"+
                jSpinnerCantPersonas.getValue()+"-"+
                jSpinnerCantDias.getValue()+"-"+
                jComboTipoAlojamiento.getSelectedItem()+"-"+
                categoriaAlojamiento()+"-"+
                jTextPrecioAlojamiento.getValue()+"-"+
                jComboTipoTransporte.getSelectedItem()+"-"+
                categoriaTransporte()+"-"+
                jTextPrecioTransporte.getValue()
            );
            jLabelAdvertenciaDestino.setVisible(false);
            jLabelAdvertenciaPrecioA.setVisible(false);
            jLabelAdvertenciaPrecioT.setVisible(false);
        } else {
            if ("".equals(jTextDestino.getText())){
                jLabelAdvertenciaDestino.setVisible(true);
            } else {
                jLabelAdvertenciaDestino.setVisible(false);
            }
            if (jTextPrecioAlojamiento.getValue()==null){
                jLabelAdvertenciaPrecioA.setVisible(true);
            } else {
                 jLabelAdvertenciaPrecioA.setVisible(false);
            }
            if (jTextPrecioTransporte.getValue()==null){
                jLabelAdvertenciaPrecioT.setVisible(true);
            } else {
                jLabelAdvertenciaPrecioT.setVisible(false);
            }
        }
    }//GEN-LAST:event_jButtonCrearAgenteActionPerformed

    private void jComboTipoTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipoTransporteActionPerformed

    private void jButtonTEstrella5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTEstrella5ActionPerformed
        jButtonTEstrella1.setSelected(true);
        jButtonTEstrella2.setSelected(true);
        jButtonTEstrella3.setSelected(true);
        jButtonTEstrella4.setSelected(true);
        jButtonTEstrella5.setSelected(true);
    }//GEN-LAST:event_jButtonTEstrella5ActionPerformed

    private void jButtonTEstrella4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTEstrella4ActionPerformed
        jButtonTEstrella1.setSelected(true);
        jButtonTEstrella2.setSelected(true);
        jButtonTEstrella3.setSelected(true);
        jButtonTEstrella4.setSelected(true);
        jButtonTEstrella5.setSelected(false);
    }//GEN-LAST:event_jButtonTEstrella4ActionPerformed

    private void jButtonTEstrella3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTEstrella3ActionPerformed
        jButtonTEstrella1.setSelected(true);
        jButtonTEstrella2.setSelected(true);
        jButtonTEstrella3.setSelected(true);
        jButtonTEstrella4.setSelected(false);
        jButtonTEstrella5.setSelected(false);
    }//GEN-LAST:event_jButtonTEstrella3ActionPerformed

    private void jButtonTEstrella2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTEstrella2ActionPerformed
        jButtonTEstrella1.setSelected(true);
        jButtonTEstrella2.setSelected(true);
        jButtonTEstrella3.setSelected(false);
        jButtonTEstrella4.setSelected(false);
        jButtonTEstrella5.setSelected(false);
    }//GEN-LAST:event_jButtonTEstrella2ActionPerformed

    private void jButtonTEstrella1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTEstrella1ActionPerformed
        jButtonTEstrella1.setSelected(true);
        jButtonTEstrella2.setSelected(false);
        jButtonTEstrella3.setSelected(false);
        jButtonTEstrella4.setSelected(false);
        jButtonTEstrella5.setSelected(false);

    }//GEN-LAST:event_jButtonTEstrella1ActionPerformed

    private void jButtonAEstrella5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAEstrella5ActionPerformed
        jButtonAEstrella1.setSelected(true);
        jButtonAEstrella2.setSelected(true);
        jButtonAEstrella3.setSelected(true);
        jButtonAEstrella4.setSelected(true);
        jButtonAEstrella5.setSelected(true);
    }//GEN-LAST:event_jButtonAEstrella5ActionPerformed

    private void jButtonAEstrella4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAEstrella4ActionPerformed
        jButtonAEstrella1.setSelected(true);
        jButtonAEstrella2.setSelected(true);
        jButtonAEstrella3.setSelected(true);
        jButtonAEstrella4.setSelected(true);
        jButtonAEstrella5.setSelected(false);
    }//GEN-LAST:event_jButtonAEstrella4ActionPerformed

    private void jButtonAEstrella3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAEstrella3ActionPerformed
        jButtonAEstrella1.setSelected(true);
        jButtonAEstrella2.setSelected(true);
        jButtonAEstrella3.setSelected(true);
        jButtonAEstrella4.setSelected(false);
        jButtonAEstrella5.setSelected(false);
    }//GEN-LAST:event_jButtonAEstrella3ActionPerformed

    private void jButtonAEstrella2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAEstrella2ActionPerformed
        jButtonAEstrella1.setSelected(true);
        jButtonAEstrella2.setSelected(true);
        jButtonAEstrella3.setSelected(false);
        jButtonAEstrella4.setSelected(false);
        jButtonAEstrella5.setSelected(false);
    }//GEN-LAST:event_jButtonAEstrella2ActionPerformed

    private void jButtonAEstrella1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAEstrella1ActionPerformed
        jButtonAEstrella1.setSelected(true);
        jButtonAEstrella2.setSelected(false);
        jButtonAEstrella3.setSelected(false);
        jButtonAEstrella4.setSelected(false);
        jButtonAEstrella5.setSelected(false);
    }//GEN-LAST:event_jButtonAEstrella1ActionPerformed

    private void jComboTipoAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoAlojamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipoAlojamientoActionPerformed

    private void jTextDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDestinoActionPerformed

    private void jButtonInfoTranporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoTranporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInfoTranporteActionPerformed

    private void jButtonCrearAgente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearAgente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCrearAgente1ActionPerformed

    private void jTextPrecioAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPrecioAlojamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPrecioAlojamientoActionPerformed

    private void jMenuItemJADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemJADEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemJADEActionPerformed

    private void jButtonCrearAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearAgenciaActionPerformed
        // Imprime por consola ponderacPrecio-ponderacCategoría
        System.out.println((jSliderPonderacion.getValue()/10.0)+"-"+((10-jSliderPonderacion.getValue())/10.0));
    }//GEN-LAST:event_jButtonCrearAgenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jButtonAEstrella1;
    private javax.swing.JRadioButton jButtonAEstrella2;
    private javax.swing.JRadioButton jButtonAEstrella3;
    private javax.swing.JRadioButton jButtonAEstrella4;
    private javax.swing.JRadioButton jButtonAEstrella5;
    private javax.swing.JToggleButton jButtonAgencia;
    private javax.swing.JToggleButton jButtonAlojamiento;
    private javax.swing.JButton jButtonCrearAgencia;
    private javax.swing.JButton jButtonCrearAgente;
    private javax.swing.JButton jButtonCrearAgente1;
    private javax.swing.JButton jButtonInfoAlojamiento;
    private javax.swing.JButton jButtonInfoTranporte;
    private javax.swing.JRadioButton jButtonTEstrella1;
    private javax.swing.JRadioButton jButtonTEstrella2;
    private javax.swing.JRadioButton jButtonTEstrella3;
    private javax.swing.JRadioButton jButtonTEstrella4;
    private javax.swing.JRadioButton jButtonTEstrella5;
    private javax.swing.JToggleButton jButtonTransporte;
    private javax.swing.JToggleButton jButtonTurista;
    private javax.swing.JComboBox jComboTipoAlojamiento;
    private javax.swing.JComboBox jComboTipoTransporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAdvertenciaDestino;
    private javax.swing.JLabel jLabelAdvertenciaPrecioA;
    private javax.swing.JLabel jLabelAdvertenciaPrecioT;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JCheckBoxMenuItem jMenuItemAdmin;
    private javax.swing.JMenuItem jMenuItemJADE;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JPanel jPanelAgencia;
    private javax.swing.JPanel jPanelAlojamiento;
    private javax.swing.JPanel jPanelTransporte;
    private javax.swing.JPanel jPanelTurista;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSlider jSliderPonderacion;
    private javax.swing.JSpinner jSpinnerCantDias;
    private javax.swing.JSpinner jSpinnerCantPersonas;
    private javax.swing.JTextField jTextDestino;
    private javax.swing.JFormattedTextField jTextPrecioAlojamiento;
    private javax.swing.JFormattedTextField jTextPrecioTransporte;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
